name: "TODOs have links"
description: "Verifies that TODOs in your codebase have a link to a follow-up issue."
author: "Nikola Irinchev"
inputs:
    token:
        required: true
        description: The Github token for this repository.
    exclude:
        required: false
        description: A glob specifying a pattern for excluding files from processing.
    include:
        required: false
        description: A glob specifying a pattern for including files to process.
        default: "**/*"
    pattern:
        required: false
        description: A Regex pattern that will be matched against the TODO text. If it matches, the TODO entry will be considered valid.
runs:
    using: "node16"
    main: "dist/index.js"
branding:
    icon: "external-link"
    color: "purple"
