name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
    token:
        required: true
        description: "The Github token for this repository"
runs:
    using: "node12"
    main: "dist/index.js"
